// NEON STICK DUEL string table [zh-HK, en]
import { i18n } from 'cyber-kit';
i18n.add({
  'doc.title': ['霓虹火柴人對決 NEON STICK DUEL · 單指 3D 格鬥', 'NEON STICK DUEL · one-thumb 3D duel'],
  you: ['你', 'YOU'], score: ['分數', 'SCORE'],
  'g.tap': ['撳', 'TAP'], 'g.tapS': ['出拳', 'punch'], 'g.hold': ['長按', 'HOLD'], 'g.holdS': ['蓄力', 'charge'],
  'g.up': ['上掃', 'SWIPE ↑'], 'g.upS': ['跳', 'jump'], 'g.side': ['橫掃', 'SWIPE ↔'], 'g.sideS': ['衝刺', 'dash'], 'g.down': ['下掃', 'SWIPE ↓'], 'g.downS': ['格擋', 'parry'],
  pauseTip: ['暫停 (P / Esc)', 'Pause (P / Esc)'], muteTip: ['靜音 (M)', 'Mute (M)'],
  kicker: ['NEON KOWLOON · 天台塔', 'NEON KOWLOON · ROOFTOP TOWER'],
  title: ['霓虹火柴人', 'NEON STICK'], titleEn: ['NEON STICK DUEL', 'ONE-THUMB DUEL'],
  tagline: ['一隻手指就打得！撳一下出拳、長按蓄力重擊、滑動跳躍／衝刺／格擋。<br>天台塔無限咁高 —— 睇你可以打上幾多層。', 'Fight with one thumb! Tap to punch, hold to charge a heavy, swipe to jump / dash / parry.<br>The rooftop tower never ends — how high can you climb?'],
  climb: ['登塔', 'CLIMB'], climbS: ['CLIMB THE TOWER · ENTER', 'START · ENTER'],
  cont: ['繼續 {f}F', 'CONTINUE {f}F'], contS: ['{name} · ENTER', '{name} · ENTER'],
  newRun: ['由 1 樓重新開始', 'NEW RUN FROM 1F'], newRunS: ['NEW TOWER RUN', 'RESET PROGRESS'],
  touchHint: ['手機：撳＝出拳（連撳三下＝三連擊）· 長按＝蓄力 · 上／橫／下掃＝跳／衝刺／格擋', 'Touch: tap = punch (tap ×3 = combo) · hold = charge · swipe up / side / down = jump / dash / parry'],
  keysHint: ['<kbd>J</kbd>/<kbd>Space</kbd> 出拳　按住 <kbd>K</kbd> 蓄力　<kbd>↑</kbd> 跳　<kbd>←</kbd><kbd>→</kbd> 衝刺　<kbd>↓</kbd> 格擋　<kbd>P</kbd> 暫停', '<kbd>J</kbd>/<kbd>Space</kbd> punch　hold <kbd>K</kbd> charge　<kbd>↑</kbd> jump　<kbd>←</kbd><kbd>→</kbd> dash　<kbd>↓</kbd> parry　<kbd>P</kbd> pause'],
  bestFloor: ['最高樓層', 'BEST FLOOR'], bestScore: ['最高分', 'BEST SCORE'], privacy: ['私隱政策', 'Privacy policy'],
  paused: ['已暫停', 'PAUSED'], pausedS: ['PAUSED', '已暫停'], resume: ['繼續', 'RESUME'], resumeS: ['RESUME · P', 'P'], quit: ['離開天台', 'QUIT'], quitS: ['QUIT · MAIN MENU', 'MAIN MENU'],
  revive: ['原地復活', 'REVIVE'], reviveAd: ['50% 血 · 睇廣告', '50% HP · WATCH AD'], reviveFree: ['50% 血 · 免費', '50% HP · FREE'],
  menu: ['主畫面', 'MAIN MENU'], menuS: ['MAIN MENU', '主畫面'], loading: ['霓虹四肢充電中…', 'CHARGING NEON LIMBS…'],
  floorBanner: ['{f} 樓 · {name}', '{f}F · {name}'], floorTag: ['{f}F', '{f}F'], endlessTag: ['無盡', 'ENDLESS'],
  fight: ['開打！', 'FIGHT!'], fightS: ['FIGHT!', '開打！'], ko: ['K.O.', 'K.O.'], down: ['倒地', 'DOWN'], knockout: ['擊倒', 'KNOCK OUT'],
  parry: ['格擋！', 'PARRY!'], evade: ['閃避', 'EVADE'], guardBreak: ['破防！', 'GUARD BREAK!'], hits: ['{n} 連擊', '{n} HITS'],
  revived: ['復活！', 'REVIVED!'], milestone: ['里程碑 {f}F！', 'MILESTONE {f}F!'], milestoneS: ['+5000 · 新區域', '+5000 · NEW DISTRICT'],
  victory: ['勝利！', 'VICTORY!'], defeat: ['戰敗…', 'DEFEATED…'], draw: ['打和', 'DRAW'],
  koWin: ['K.O. 勝', 'K.O. VICTORY'], decWin: ['判定勝', 'DECISION WIN'], gotKo: ['你被 K.O.', 'YOU GOT K.O.'], timeOver: ['時間到', 'TIME OVER'],
  sFloor: ['樓層獎勵', 'Floor bonus'], sHp: ['剩餘血量', 'HP bonus'], sTime: ['時間獎勵', 'Time bonus'], sTotal: ['總分', 'Total'], sPerfect: ['完美', 'Perfect'], sMilestone: ['里程碑', 'Milestone'],
  sHits: ['命中', 'Hits'], sParries: ['格擋', 'Parries'], sFoeHp: ['對手剩血', 'Foe HP'],
  next: ['上一層', 'NEXT FLOOR'], nextS: ['NEXT FLOOR · ENTER', 'ENTER'], retry: ['再挑戰', 'RETRY'], retryS: ['RETRY FLOOR · ENTER', 'ENTER'],
  endlessUnlocked: ['塔頂之上仲有更多層 —— 無盡模式開始！', 'There is more above the top — endless mode begins!'],
});
